config/urls.py
import debug_toolbar

from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.urls import re_path
from django.views.static import serve

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('discotheque/', include('discotheque.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
] 
if settings.DEBUG:
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {
            'document_root': 'media',
        }),
    ]

discotheque/urls.py
from django.urls import path

from . import views

app_name = 'discotheque'
urlpatterns = [
    path('', views.index, name='index'),
    # ex: /polls/5/
    path('<int:groupe_id>/', views.detail, name='detail'),
    # # ex: /polls/5/results/
    # path('<int:question_id>/results/', views.results, name='results'),
    # # ex: /polls/5/vote/
    # path('<int:question_id>/vote/', views.vote, name='vote'),
]

discotheque/models.py
from django.db import models
from django.db.models.deletion import CASCADE


class Groupe(models.Model):
    nom_groupe = models.CharField(max_length=200)
    groupe_image = models.ImageField(upload_to='media')
    
    def __str__(self):
        return self.nom_groupe

class Album(models.Model):
    nom_album = models.CharField(max_length=200)
    id_groupe = models.ForeignKey(Groupe, models.SET_NULL, blank=True, null=True,)

    def __str__(self):
        return self.nom_album    

class Support(models.Model):
    type_support = models.CharField(max_length=200)

    def __str__(self):
        return self.type_support

class Album_support(models.Model):
    id_album = models.ForeignKey(Album, models.SET_NULL, blank=True, null=True,)        
    id_support = models.ForeignKey(Support, models.SET_NULL, blank=True, null=True,)        
    

config/views.py
from django.shortcuts import render

def home(request):
    return render (request, 'home.html')

discotheque/views.py
from django.shortcuts import render
from django.template import loader

from django.http import HttpResponse

from .models import Groupe
from .models import Album
from .models import Support
from .models import Album_support


def index(request):
    groupe_list = Groupe.objects.order_by('nom_groupe')
    context = {
        'groupe_list': groupe_list.all(),
    }
    return render(request, 'discotheque/index.html', context)
# Create your views here.

def detail(request, groupe_id):
    album_list = Album.objects.filter(id_groupe = groupe_id)
    group = Groupe.objects.get(pk = groupe_id)
    support_list = Support.objects.all()
    album_support_list = Album_support.objects.all()
    context = {
        'group' : group, 
        'album_list': album_list,
        'support_list' : support_list,
        'album_support_list': album_support_list,
    }
    return render(request, 'discotheque/album.html', context)

# def results(request, question_id):
#     response = "You're looking at the results of question %s."
#     return HttpResponse(response % question_id)

# def vote(request, question_id):
#     return HttpResponse("You're voting on question %s." % question_id)

discotheque/templates/discotheque/album.html
{% extends 'layouts/base.html' %}

{% block content %}
<h2> {{ group }} </h2>
{% if album_list %}
    <ul>
    {% for album in album_list %}
        <li>{{ album }}
            {% for album_support in album_support_list %}
                {% if album_support.id_album_id  == album.id %}
                    {% for support in support_list %}
                        {% if support.id  == album_support.id_support_id %}        
                            <p>{{ support }}</p>
                        {% endif %}
                    {% endfor %}
                {% endif %}
            {% endfor %}
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>Pas d'album disponible</p>
{% endif %}
{% endblock content %}

discotheque/templates/discotheque/index.html
{% extends 'layouts/base.html' %}

{% block content %}
{% if groupe_list %}
    <ul>
    {% for groupe in groupe_list %}
        <li>
        <a href="{% url 'discotheque:detail' groupe.id %}">{{ groupe }}</a> 
        <img src="{{ groupe.groupe_image.url }}" alt="">
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>Pas de groupe disponible</p>
{% endif %}
{% endblock content %}

templates/home.html
{% extends 'layouts/base.html' %}

{% block content %}
    <h1>Voila ma collection</h1>
{% endblock content %}

templates/layouts/_nav.html
<a href="{% url 'home' %}"><h1>RIJA COLLECTIONS</h1></a>
<a href="{% url 'discotheque:index' %}">Discothèque</a>
<a href="#">Vidéothèque</a>

templates/layouts/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'discotheque/css/discotheque.css' %}">   
    <title>{% block title %}Mes collections{% endblock %}</title>
</head>
<body>

    {% include  'layouts/_nav.html' %}
    {% block content %}{% endblock content %}

</body>
</html>